[package]
name = "gouache"
version = "0.1.0"
authors = ["Micah Johnston <micah@glowcoil.com>"]
edition = "2018"

[dependencies]
gl = "0.11.0"
ttf-parser = "0.1.0"

[dev-dependencies]
glutin = "0.21.0"
